#page-theme: skybluelines

beginInfoBox: "<div markdown='1' class='infobox'>"
endInfoBox: "</div>"
beginInfoBoxTitle: "<div class='infobox-title'>"
endInfoBoxTitle: "</div>"

beginFigure: "<div class='figure'>"
endFigure: "</div>"
beginCaption: "<p class='figure-caption'>"
endCaption: "</p>"