#page-theme: skybluelines

openInfoBox: "<div markdown='1' class='card-panel infobox'>"
closeInfoBox: "</div>"
openInfoBoxTitle: "<div class='text-bold infobox-title' style='padding-bottom: 1em; font-weight: bold; text-transform: uppercase;'>"
closeInfoBoxTitle: "</div>"