#page-theme: skybluelines

openInfoBox: "<div markdown='1' class='card-panel blue lighten-4'>"
closeInfoBox: "</div>"
openInfoBoxTitle: "<div class='blue-text text-bold text-darken-2' style='padding-bottom: 1em; font-weight: bold; text-transform: uppercase;'>"
closeInfoBoxTitle: "</div>"